// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7GjhojTjB7bT93Y2NQ2crBY5vwCOVfng',
    appId: '1:510102270850:android:126718c65ff4e1e9c0d59b',
    messagingSenderId: '510102270850',
    projectId: 'fitness-tracker-ed6fa',
    storageBucket: 'fitness-tracker-ed6fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_IsN8HxiN8ciVdS61hWqouAWqPAUEx9c',
    appId: '1:510102270850:ios:a240a0e1ab122ecfc0d59b',
    messagingSenderId: '510102270850',
    projectId: 'fitness-tracker-ed6fa',
    storageBucket: 'fitness-tracker-ed6fa.firebasestorage.app',
    androidClientId: '510102270850-0l2v0qneja0kq76i1a1icsdu8qqla3h4.apps.googleusercontent.com',
    iosClientId: '510102270850-6pg6q5ge8ls76i48ho4ie4a5l9b8ta9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitcourse',
  );
}